source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AtomeMerchantDemo' do
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'PKHUD', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
end
